// <auto-generated />
namespace Mercadinho.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0")]
    public sealed partial class alteracaocampoDatadeRecebimentoIntparaDate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(alteracaocampoDatadeRecebimentoIntparaDate));
        
        string IMigrationMetadata.Id
        {
            get { return "201911091322428_alteracao campo DatadeRecebimento Int para Date"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
